const API_URL='https://script.google.com/macros/s/AKfycbwu8lfhiH3_7m4ogHNtbgeo3ehx_VBMnt1mPXsvIlL_kMSpxFdrRD4rO_I6q_JUXIWHmg/exec';
const COMMON_TOKEN_KEY='stepCommonStudentSessionToken';
const COMMON_EXPIRES_KEY='stepCommonStudentSessionExpiresAt';
const COMMON_PROFILE_KEY='stepCommonStudentProfile';
const STAFF_SESSION_KEY='forestaStaffSession';
const state={token:'',role:'',profile:null,dashboard:null,admin:null,student:null,rangeAdmin:null,filters:{query:'',campus:'',status:''},rangeFilters:{school:'',grade:'中1',subject:'数学'}};
const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
function normalizeStudentSearch_(value){return String(value||'').normalize('NFKC').toLowerCase().replace(/[ァ-ヶ]/g,ch=>String.fromCharCode(ch.charCodeAt(0)-0x60)).replace(/[\s　]+/g,'')}
const ROMAJI_PAIRS_={
  'きゃ':'kya','きゅ':'kyu','きょ':'kyo','ぎゃ':'gya','ぎゅ':'gyu','ぎょ':'gyo',
  'しゃ':'sha','しゅ':'shu','しょ':'sho','じゃ':'ja','じゅ':'ju','じょ':'jo',
  'ちゃ':'cha','ちゅ':'chu','ちょ':'cho','ぢゃ':'ja','ぢゅ':'ju','ぢょ':'jo',
  'にゃ':'nya','にゅ':'nyu','にょ':'nyo','ひゃ':'hya','ひゅ':'hyu','ひょ':'hyo',
  'びゃ':'bya','びゅ':'byu','びょ':'byo','ぴゃ':'pya','ぴゅ':'pyu','ぴょ':'pyo',
  'みゃ':'mya','みゅ':'myu','みょ':'myo','りゃ':'rya','りゅ':'ryu','りょ':'ryo',
  'うぃ':'wi','うぇ':'we','うぉ':'wo','ゔぁ':'va','ゔぃ':'vi','ゔぇ':'ve','ゔぉ':'vo',
  'ふぁ':'fa','ふぃ':'fi','ふぇ':'fe','ふぉ':'fo','しぇ':'she','じぇ':'je','ちぇ':'che',
  'てぃ':'ti','でぃ':'di','とぅ':'tu','どぅ':'du','つぁ':'tsa','つぃ':'tsi','つぇ':'tse','つぉ':'tso'
};
const ROMAJI_CHARS_={
  'あ':'a','い':'i','う':'u','え':'e','お':'o','か':'ka','き':'ki','く':'ku','け':'ke','こ':'ko',
  'が':'ga','ぎ':'gi','ぐ':'gu','げ':'ge','ご':'go','さ':'sa','し':'shi','す':'su','せ':'se','そ':'so',
  'ざ':'za','じ':'ji','ず':'zu','ぜ':'ze','ぞ':'zo','た':'ta','ち':'chi','つ':'tsu','て':'te','と':'to',
  'だ':'da','ぢ':'ji','づ':'zu','で':'de','ど':'do','な':'na','に':'ni','ぬ':'nu','ね':'ne','の':'no',
  'は':'ha','ひ':'hi','ふ':'fu','へ':'he','ほ':'ho','ば':'ba','び':'bi','ぶ':'bu','べ':'be','ぼ':'bo',
  'ぱ':'pa','ぴ':'pi','ぷ':'pu','ぺ':'pe','ぽ':'po','ま':'ma','み':'mi','む':'mu','め':'me','も':'mo',
  'や':'ya','ゆ':'yu','よ':'yo','ら':'ra','り':'ri','る':'ru','れ':'re','ろ':'ro','わ':'wa','を':'o',
  'ん':'n','ゔ':'vu','ぁ':'a','ぃ':'i','ぅ':'u','ぇ':'e','ぉ':'o','ゎ':'wa'
};
function kanaToRomaji_(value){
  const kana=normalizeStudentSearch_(value);
  let out='',smallTsu=false;
  for(let i=0;i<kana.length;i++){
    const ch=kana[i];
    if(ch==='っ'){smallTsu=true;continue}
    if(ch==='ー'){const vowel=(out.match(/[aeiou]$/)||[])[0];if(vowel)out+=vowel;continue}
    const pair=ROMAJI_PAIRS_[kana.slice(i,i+2)];
    let roma=pair||ROMAJI_CHARS_[ch]||ch;
    if(pair)i++;
    if(smallTsu){if(roma.startsWith('ch'))out+='t';else if(/^[bcdfghjklmpqrstvwxyz]/.test(roma))out+=roma[0];smallTsu=false}
    out+=roma;
  }
  return out;
}

async function api(action,payload={}){
  const response=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({...payload,action,token:state.token}),cache:'no-store',redirect:'follow'});
  if(!response.ok)throw new Error('サーバーへ接続できませんでした。');
  const result=await response.json();
  if(!result.success)throw new Error(result.error||'処理に失敗しました。');
  return result;
}
function toast(message){const el=$('toast');el.textContent=message;el.classList.remove('hidden');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.add('hidden'),2600)}
function todayLabel(){return new Intl.DateTimeFormat('ja-JP',{year:'numeric',month:'long',day:'numeric',weekday:'short'}).format(new Date())}
function saveSession(kind,result){state.token=result.token;state.role=result.role;state.profile=result.profile||{};if(kind==='student'){localStorage.setItem(COMMON_TOKEN_KEY,result.token);localStorage.setItem(COMMON_EXPIRES_KEY,result.expiresAt||'');localStorage.setItem(COMMON_PROFILE_KEY,JSON.stringify(result.profile||{}))}else sessionStorage.setItem(STAFF_SESSION_KEY,JSON.stringify({token:result.token,role:result.role,profile:result.profile,expiresAt:result.expiresAt}))}
function clearSession(){state.token='';state.role='';state.profile=null;localStorage.removeItem(COMMON_TOKEN_KEY);localStorage.removeItem(COMMON_EXPIRES_KEY);localStorage.removeItem(COMMON_PROFILE_KEY);sessionStorage.removeItem(STAFF_SESSION_KEY)}
function renderLoading(label='データを読み込んでいます…'){$('app').innerHTML=`<div class="loading">${esc(label)}</div>`}

function statusMeta(code){const map={AHEAD:['学校より先','status-ahead'],AT_SCHOOL:['学校と同じ','status-warning'],BEHIND:['学校より遅れ','status-danger'],RANGE_COMPLETE:['予想範囲完了','status-ahead'],REPEAT:['範囲を反復','status-ahead'],NO_DATA:['未入力','status-muted']};return map[code]||map.NO_DATA}
function ctMeta(value){if(value==='◎')return ['◎','ct-good'];if(value==='〇'||value==='○')return ['〇','ct-mid'];if(value==='×')return ['×','ct-bad'];return ['未実施','status-muted']}
function statusPill(code){const [label,klass]=statusMeta(code);return `<span class="status-pill ${klass}">${label}</span>`}
function ctPill(value){const [label,klass]=ctMeta(value);return `<span class="ct-pill ${klass}">${label}</span>`}
function scoreRows(scores=[],editable=false,loading=false){const colspan=editable?6:5;if(loading)return `<tr><td colspan="${colspan}" class="score-loading">成績履歴を読み込み中…</td></tr>`;return scores.slice().sort((a,b)=>String(b.year).localeCompare(String(a.year))||String(b.term).localeCompare(String(a.term))).map(s=>`<tr><td>${esc(s.year)}年 ${esc(s.term)}回</td><td>${esc(s.eng??'—')}</td><td>${esc(s.math??'—')}</td><td>${esc(s.total5??'—')}</td><td>${esc(s.rank5??'—')}</td>${editable?`<td><button type="button" class="score-edit-button" data-score-year="${esc(s.year)}" data-score-term="${esc(s.term)}">訂正</button></td>`:''}</tr>`).join('')||`<tr><td colspan="${colspan}">定期テストの登録はまだありません</td></tr>`}
function homeworkItems(subject,items=[]){const defaults=subject==='英語'?['Key Words「☆日→英」暗記','Exercise「暗記マーク」暗記','TRY赤×直し','Exercise','前回宿題の赤×直し']:['TRY赤×直し','Exercise','前回宿題の赤×直し'];return (items.length?items:defaults).map(item=>{const data=typeof item==='string'?{label:item}:item||{};return `<div class="homework-item ${data.completedAt?'is-complete':''}"><i>${data.completedAt?'✓':'□'}</i><span>${esc(data.label||data.type)}${data.completedAt?`<small>完了日 ${esc(data.completedAt)}</small>`:''}</span></div>`}).join('')}
function lessonUnitLabel_(lesson){const codes=lesson?.progressCodes||[];return codes.length?codes.join('・'):[lesson?.startCode,lesson?.endCode].filter(Boolean).join('〜')}
function targetScoreForm_(d,id){const targets=d.targetScores||{};return `<form id="${id}" class="target-score-form"><label><span>英語</span><input name="english" type="number" min="0" max="100" value="${esc(targets['英語']??'')}" placeholder="—"><i>点</i></label><label><span>数学</span><input name="math" type="number" min="0" max="100" value="${esc(targets['数学']??'')}" placeholder="—"><i>点</i></label><button type="submit" class="action-button primary">目標点を保存</button><small class="form-message"></small></form>`}
function bindTargetScoreForm_(id,d,studentId){const form=$(id);if(!form)return;form.onsubmit=async event=>{event.preventDefault();const button=form.querySelector('button'),message=form.querySelector('.form-message'),values=Object.fromEntries(new FormData(form).entries());button.disabled=true;button.textContent='保存中…';message.textContent='';try{const out=await api('saveForestaTargetScores',{studentId,...values});d.targetScores=out.targetScores;toast('今回の目標点を保存しました。');button.textContent='保存しました';setTimeout(()=>{button.disabled=false;button.textContent='目標点を保存'},900)}catch(error){message.textContent=error.message;button.disabled=false;button.textContent='目標点を保存'}}}

async function loadScoresInto_(d,bodyId,editable){const body=$(bodyId);if(!body)return;try{const out=await api('getForestaScores',{studentId:d.student?.studentId});if((state.dashboard!==d&&state.student!==d)||!$(bodyId))return;d.scores=out.scores||[];$(bodyId).innerHTML=scoreRows(d.scores,editable,false);if(editable)bindScoreEditButtons_(d)}catch(error){if($(bodyId))$(bodyId).innerHTML=`<tr><td colspan="${editable?6:5}" class="form-message">${esc(error.message)}</td></tr>`}}
async function loadStudent(){renderLoading();const out=await api('getForestaDashboard');state.dashboard=out.data;renderStudent();loadScoresInto_(state.dashboard,'studentScoreRows',false)}
function renderStudent(){const d=state.dashboard||{},subject=d.subject||'数学',pace=d.pace||{},next=d.nextTest||{},latest=d.latestLesson||{};const alarm=d.status==='BEHIND'||d.status==='AT_SCHOOL';$('sessionName').textContent=(state.profile?.name||d.student?.name||'')+'さん';$('logoutButton').classList.remove('hidden');$('app').innerHTML=`
  <div class="page-head"><div><span class="eyebrow">MY FORESTA</span><h1>${esc(d.student?.name||state.profile?.name||'')}さん</h1><p>${esc(d.student?.school||'学校未登録')}｜${esc(d.student?.grade||'')}</p></div><span class="date-chip">${todayLabel()}</span></div>
  ${alarm?'<div class="alarm-banner">⚠ フォレスタが学校進度より先になっていません。次の授業で進度を確認してください。</div>':'<div class="success-banner">✓ 学校より先の範囲を学習できています。</div>'}
  <div class="summary-grid"><div class="summary-card ${alarm?'alert':'good'}"><span>学校との位置</span><strong>${statusPill(d.status)}</strong><small>${esc(subject)} ${esc(d.aheadUnits??0)}単元先</small></div><div class="summary-card"><span>予想範囲まで</span><strong>${esc(pace.remainingUnits??'—')} 単元</strong><small>飛ばせる難度を除外</small></div><div class="summary-card"><span>残り授業回数</span><strong>${esc(pace.remainingLessons??'—')} 回</strong><small>${esc(next.name||'次回テスト')}の2週間前まで</small></div><div class="summary-card"><span>必要ペース</span><strong>${esc(pace.requiredPerLesson??'—')} 単元/回</strong><small>${esc(next.date||'日程未登録')}</small></div></div>
  <div class="detail-grid"><div class="stack"><section class="panel"><div class="panel-head"><div><span class="eyebrow">LATEST LESSON</span><h2>今回の授業</h2></div>${ctPill(latest.ctResult)}</div><div class="pace-line"><div class="pace-item"><span>科目</span><b>${esc(latest.subject||subject)}</b></div><div class="pace-item"><span>進んだ単元</span><b>${esc(latest.progressedUnits??0)}</b></div><div class="pace-item"><span>担当</span><b>${esc(latest.instructorName||'—')}</b></div><div class="pace-item"><span>前回宿題</span><b>${latest.homeworkCompleted==='YES'?'完了':latest.homeworkCompleted==='PARTIAL'?'一部完了':latest.homeworkCompleted==='NO'?'未完了':'—'}</b></div></div></section><section class="panel"><div class="panel-head"><div><span class="eyebrow">NEXT HOMEWORK</span><h2>次回の宿題</h2></div></div><div class="homework-list">${homeworkItems(subject,latest.homeworkItems||[])}</div></section><section class="panel"><div class="panel-head"><div><span class="eyebrow">LESSON HISTORY</span><h2>授業履歴</h2></div></div><div class="history-list">${(d.lessons||[]).map(x=>`<div class="history-row"><b>${esc(x.lessonDate)}｜${esc(x.subject)} ${esc(lessonUnitLabel_(x)||'単元未登録')}</b><span>CT ${esc(x.ctResult||'未実施')}｜${esc(x.progressedUnits||0)}単元｜担当 ${esc(x.instructorName||'—')}</span></div>`).join('')||'<div class="empty">授業記録はまだありません</div>'}</div></section></div>
  <div class="stack"><section class="panel"><div class="panel-head"><div><span class="eyebrow">CLEAR TEST</span><h2>次回クリアテスト</h2></div>${ctPill(latest.ctResult)}</div><p><b>${esc(latest.nextCtCode||'今回進んだ範囲から先生が1単元選びます')}</b></p><p class="help">◎ 全問正解　〇 1問間違い　× 2問以上間違い（特訓部屋）</p></section><section class="panel"><div class="panel-head"><div><span class="eyebrow">SCORE HISTORY</span><h2>今回の目標点と定期テスト履歴</h2></div></div>${targetScoreForm_(d,'studentTargetScores')}<div class="table-wrap"><table class="score-table"><thead><tr><th>テスト</th><th>英</th><th>数</th><th>5科</th><th>順位</th></tr></thead><tbody id="studentScoreRows">${scoreRows(d.scores,false,d.scoresDeferred&&!d.scores?.length)}</tbody></table></div></section></div></div>`;bindTargetScoreForm_('studentTargetScores',d,d.student?.studentId)}

async function loadAdmin(){renderLoading('本日の進捗一覧を読み込んでいます…');const out=await api('getForestaAdminDashboard');state.admin=out;renderAdmin()}
function filteredStudents(){const q=normalizeStudentSearch_(state.filters.query);return (state.admin?.students||[]).filter(s=>{const kana=s.kana||s.furigana||'';const values=[s.studentId,s.name,kana,s.school].map(normalizeStudentSearch_);values.push(kanaToRomaji_(kana));return(!q||values.some(v=>v.includes(q)))&&(!state.filters.campus||s.campus===state.filters.campus)&&(!state.filters.status||s.status===state.filters.status)})}
function adminStudentRowsHtml_(){const list=filteredStudents();return list.map(s=>{const target=s.targetScores||{},homework=s.homeworkCompleted==='YES'?'<span class="status-pill status-ahead">完了</span>':s.homeworkCompleted==='PARTIAL'?`<span class="status-pill status-warning">一部（未完了 ${esc(s.homeworkIncompleteCount??'—')}）</span>`:s.homeworkCompleted==='NO'?`<span class="status-pill status-danger">未完了 ${esc(s.homeworkIncompleteCount??'')}</span>`:'<span class="status-pill status-muted">記録なし</span>';return `<tr data-student-id="${esc(s.studentId)}"><td class="student-cell"><b>${esc(s.name)}</b><small>${esc(s.grade)}｜${esc(s.school||'学校未登録')}</small></td><td>${esc(s.campus)}</td><td>${esc(s.subject||'—')}</td><td>${statusPill(s.status)}</td><td>${homework}</td><td>${ctPill(s.ctResult)}</td><td>英 ${esc(target['英語']??'—')}<br>数 ${esc(target['数学']??'—')}</td><td>${esc(s.todayProgressedUnits??0)}単元</td><td>${esc(s.remainingUnits??'—')}単元</td><td>${esc(s.remainingLessons??'—')}回</td><td><b>${esc(s.requiredPerLesson??'—')}単元/回</b></td><td>${esc(s.instructorName||'未入力')}</td></tr>`}).join('')||'<tr><td colspan="12" class="empty">条件に合う生徒はいません</td></tr>'}
function bindAdminStudentRows_(){document.querySelectorAll('[data-student-id]').forEach(row=>row.onclick=()=>openStudent(row.dataset.studentId))}
function refreshAdminStudentRows_(){$('adminStudentRows').innerHTML=adminStudentRowsHtml_();bindAdminStudentRows_()}
function renderAdmin(){const all=state.admin?.students||[],campuses=[...new Set(all.map(x=>x.campus).filter(Boolean))];$('sessionName').textContent=(state.profile?.name||'管理者')+'さん';$('logoutButton').classList.remove('hidden');$('app').innerHTML=`
  <div class="page-head"><div><span class="eyebrow">TODAY OVERVIEW</span><h1>本日の進捗状況</h1><p>学校進度・宿題・CT・必要ペースを優先順で確認します。</p></div><div class="header-actions">${state.role==='ADMIN'?'<button id="openRangeAdmin" class="action-button primary">予想テスト範囲設定</button>':''}<span class="date-chip">${todayLabel()}</span></div></div>
  <div class="summary-grid"><div class="summary-card"><span>在籍生</span><strong>${all.length}名</strong><small>英語・数学</small></div><div class="summary-card alert"><span>学校進度アラーム</span><strong>${all.filter(x=>['BEHIND','AT_SCHOOL'].includes(x.status)).length}名</strong><small>学校より先になっていない</small></div><div class="summary-card"><span>CT不合格</span><strong>${all.filter(x=>x.ctResult==='×').length}名</strong><small>特訓部屋の連絡対象</small></div><div class="summary-card"><span>本日未入力</span><strong>${all.filter(x=>!x.todayRecorded).length}名</strong><small>授業後に入力</small></div></div>
  <div class="toolbar"><input id="studentSearch" value="${esc(state.filters.query)}" placeholder="生徒コード・氏名・フリガナ・ローマ字で検索" autocomplete="off"><select id="campusFilter"><option value="">すべての教室</option>${campuses.map(v=>`<option ${state.filters.campus===v?'selected':''}>${esc(v)}</option>`).join('')}</select><select id="statusFilter"><option value="">すべての状況</option><option value="BEHIND" ${state.filters.status==='BEHIND'?'selected':''}>学校より遅れ</option><option value="AT_SCHOOL" ${state.filters.status==='AT_SCHOOL'?'selected':''}>学校と同じ</option><option value="AHEAD" ${state.filters.status==='AHEAD'?'selected':''}>学校より先</option><option value="NO_DATA" ${state.filters.status==='NO_DATA'?'selected':''}>未入力</option></select><button id="refreshButton" class="action-button">更新</button></div>
  <section class="panel table-wrap"><table class="progress-table"><thead><tr><th>生徒</th><th>教室</th><th>科目</th><th>学校との位置</th><th>前回宿題</th><th>CT</th><th>目標点</th><th>本日</th><th>予想範囲まで</th><th>残り回数</th><th>必要ペース</th><th>担当</th></tr></thead><tbody id="adminStudentRows">${adminStudentRowsHtml_()}</tbody></table></section>`;
  $('studentSearch').oninput=e=>{state.filters.query=e.target.value;refreshAdminStudentRows_()};$('campusFilter').onchange=e=>{state.filters.campus=e.target.value;refreshAdminStudentRows_()};$('statusFilter').onchange=e=>{state.filters.status=e.target.value;refreshAdminStudentRows_()};$('refreshButton').onclick=loadAdmin;if($('openRangeAdmin'))$('openRangeAdmin').onclick=loadRangeAdmin;bindAdminStudentRows_()}

async function loadRangeAdmin(){renderLoading('学校別の予想テスト範囲を読み込んでいます…');const out=await api('getForestaRangeAdminData');state.rangeAdmin=out;renderRangeAdmin()}
function currentRangeSetting_(school,grade,subject){return (state.rangeAdmin?.settings||[]).find(row=>row.school===school&&row.grade===grade&&row.subject===subject)||null}
function rangeUnits_(grade,subject){return state.rangeAdmin?.units?.[`${grade}|${subject}`]||[]}
function rangeUnitCheckboxes_(units,selectedIds=[]){const selected=new Set((selectedIds||[]).map(String));return `<div class="unit-check-list range-check-list">${(units||[]).map(u=>`<label class="unit-check"><input type="checkbox" name="predictedRangeUnitIds" value="${esc(u.unitId)}" ${selected.has(String(u.unitId))?'checked':''}><span><b>${esc(u.stepCode)}</b> ${esc(u.unitTitle)}</span></label>`).join('')}</div>`}
function rangeMatrixRows_(){const d=state.rangeAdmin||{};return (d.schools||[]).flatMap(school=>['中1','中2','中3'].flatMap(grade=>['英語','数学'].map(subject=>{const setting=currentRangeSetting_(school.name,grade,subject),test=school.tests?.[grade]||{},codes=setting?.predictedRangeCodes||[];return `<tr><td><b>${esc(school.name)}</b></td><td>${esc(grade)}</td><td>${esc(subject)}</td><td>${esc(test.name||'次回定期テスト')}<small>${esc(test.date||'日程未登録')}</small></td><td>${setting?`<b>${esc(codes.join('・'))}</b><small>${codes.length}単元を選択</small>`:'<span class="status-pill status-warning">未設定</span>'}</td><td><button type="button" class="action-button" data-range-edit data-school="${esc(school.name)}" data-grade="${esc(grade)}" data-subject="${esc(subject)}">${setting?'変更':'設定'}</button></td></tr>`}))).join('')||'<tr><td colspan="6" class="empty">中学校情報がありません</td></tr>'}
function renderRangeAdmin(){const d=state.rangeAdmin||{},schools=d.schools||[];if(!schools.some(item=>item.name===state.rangeFilters.school))state.rangeFilters.school=schools[0]?.name||'';if(!['中1','中2','中3'].includes(state.rangeFilters.grade))state.rangeFilters.grade='中1';if(!['英語','数学'].includes(state.rangeFilters.subject))state.rangeFilters.subject='数学';const f=state.rangeFilters,current=currentRangeSetting_(f.school,f.grade,f.subject),units=rangeUnits_(f.grade,f.subject),school=schools.find(item=>item.name===f.school)||{},nextTest=school.tests?.[f.grade]||{};$('app').innerHTML=`
  <div class="page-head"><div><button id="backToAdmin" class="back-button">← 本日の一覧</button><span class="eyebrow">TEST RANGE SETTINGS</span><h1>予想テスト範囲設定</h1><p>中学校・学年・科目ごとに、次回定期テストに含まれる単元を選択します。</p></div></div>
  <section class="panel"><div class="panel-head"><div><span class="eyebrow">NEXT TEST</span><h2>次回までの範囲</h2></div><span class="date-chip">${esc(nextTest.name||'次回定期テスト')}｜${esc(nextTest.date||'日程未登録')}</span></div><form id="rangeSettingForm" class="form-grid"><label class="field"><span>中学校</span><select id="rangeSchool" name="school" required>${schools.map(item=>`<option value="${esc(item.name)}" ${item.name===f.school?'selected':''}>${esc(item.name)}</option>`).join('')}</select></label><label class="field"><span>学年</span><select id="rangeGrade" name="grade"><option ${f.grade==='中1'?'selected':''}>中1</option><option ${f.grade==='中2'?'selected':''}>中2</option><option ${f.grade==='中3'?'selected':''}>中3</option></select></label><label class="field"><span>科目</span><select id="rangeSubject" name="subject"><option ${f.subject==='英語'?'selected':''}>英語</option><option ${f.subject==='数学'?'selected':''}>数学</option></select></label><div class="field full"><span>予想テスト範囲の単元（複数選択可）</span>${rangeUnitCheckboxes_(units,current?.predictedRangeUnitIds||[])}<p class="help">テスト範囲が飛び飛びの場合も、含まれる単元だけにチェックしてください。残り単元数と必要ペースは、チェックした単元だけで計算します。</p></div><button id="saveRangeSetting" class="primary-button" type="submit" ${schools.length?'':'disabled'}>この予想範囲を保存</button><p id="rangeMessage" class="form-message"></p></form></section>
  <section class="panel table-wrap" style="margin-top:16px"><div class="panel-head"><div><span class="eyebrow">ALL SETTINGS</span><h2>学校別の設定一覧</h2></div></div><table class="progress-table"><thead><tr><th>中学校</th><th>学年</th><th>科目</th><th>次回テスト</th><th>選択した単元</th><th>操作</th></tr></thead><tbody>${rangeMatrixRows_()}</tbody></table></section>`;
  $('backToAdmin').onclick=renderAdmin;$('rangeSchool').onchange=e=>{state.rangeFilters.school=e.target.value;renderRangeAdmin()};$('rangeGrade').onchange=e=>{state.rangeFilters.grade=e.target.value;renderRangeAdmin()};$('rangeSubject').onchange=e=>{state.rangeFilters.subject=e.target.value;renderRangeAdmin()};document.querySelectorAll('[data-range-edit]').forEach(button=>button.onclick=()=>{state.rangeFilters={school:button.dataset.school,grade:button.dataset.grade,subject:button.dataset.subject};renderRangeAdmin()});$('rangeSettingForm').onsubmit=async event=>{event.preventDefault();const button=$('saveRangeSetting'),form=new FormData(event.target),payload=Object.fromEntries(form.entries());payload.predictedRangeUnitIds=form.getAll('predictedRangeUnitIds');button.disabled=true;button.textContent='保存中…';try{await api('saveForestaRangeSetting',payload);toast(`${payload.school} ${payload.grade} ${payload.subject}の予想範囲を保存しました。`);await loadRangeAdmin()}catch(error){$('rangeMessage').textContent=error.message;button.disabled=false;button.textContent='この予想範囲を保存'}}}

async function openStudent(studentId){renderLoading('生徒データを読み込んでいます…');const out=await api('getForestaStudent',{studentId});state.student=out.data;renderAdminStudent();loadScoresInto_(state.student,'adminScoreRows',true)}
function unitOptions(units,value){return `<option value="">選択してください</option>`+(units||[]).map(u=>`<option value="${esc(u.unitId)}" ${String(u.unitId)===String(value)?'selected':''}>${esc(u.stepCode)} ${esc(u.unitTitle)}${u.skippable?'（省略可）':''}</option>`).join('')}
function unitCheckboxes_(units){return `<div class="unit-check-list">${(units||[]).map(u=>`<label class="unit-check"><input type="checkbox" name="progressUnitIds" value="${esc(u.unitId)}"><span><b>${esc(u.stepCode)}</b> ${esc(u.unitTitle)}${u.skippable?'<small>省略可</small>':''}</span></label>`).join('')}</div>`}
function homeworkCheckboxes_(items){if(!items?.length)return '<div class="empty compact">前回の宿題はありません</div>';return `<div class="homework-check-list">${items.map(item=>`<label class="homework-check"><input type="checkbox" name="completedHomeworkIds" value="${esc(item.homeworkId)}" ${item.completedAt?'checked':''}><span><b>${esc(item.label)}</b><small>${item.completedAt?`完了日 ${esc(item.completedAt)}`:'未完了'}</small></span></label>`).join('')}</div>`}
function lessonSubjectFields_(d,subject){const units=(d.units||[]).filter(u=>u.subject===subject),previous=d.previousHomeworkBySubject?.[subject]||[];return `<label class="field full"><span>学校の進度（必須）</span><select name="schoolProgressUnitId" required>${unitOptions(units,subject===(d.subject||'数学')?d.schoolProgressUnitId:'')}</select></label><div class="field full"><span>今回学習した単元（複数選択可）</span>${unitCheckboxes_(units)}<p class="help">同じ単元の復習や、前後して学習した場合も、実際に取り組んだ単元をすべて選んでください。</p></div><div class="field full"><span>前回の宿題</span>${homeworkCheckboxes_(previous)}<p class="help">完了した項目にチェックすると、授業日が完了日として記録されます。未チェックは未完了のまま残ります。</p></div>`}
function bindScoreEditButtons_(d){document.querySelectorAll('[data-score-year]').forEach(button=>button.onclick=()=>{const score=(d.scores||[]).find(item=>String(item.year)===button.dataset.scoreYear&&String(item.term)===button.dataset.scoreTerm);if(score)openScoreCorrectionDrawer_(d,score)})}
function scoreCorrectionField_(name,label,value,max=100){return `<label class="field"><span>${label}</span><input type="number" name="${name}" min="0" max="${max}" step="0.1" value="${esc(value??'')}"></label>`}
function openScoreCorrectionDrawer_(d,score){const root=$('drawerRoot');root.innerHTML=`<div class="drawer"><form id="scoreCorrectionForm" class="drawer-card"><div class="drawer-head"><div><span class="eyebrow">SCORE CORRECTION</span><h2>${esc(d.student.name)}さんの成績訂正</h2><p>${esc(score.year)}年度 第${esc(score.term)}回</p></div><button id="closeDrawer" class="close-button" type="button">×</button></div><input type="hidden" name="year" value="${esc(score.year)}"><input type="hidden" name="term" value="${esc(score.term)}"><div class="form-grid"><div class="field full score-section-title">5教科</div>${scoreCorrectionField_('jpn','国語',score.jpn)}${scoreCorrectionField_('soc','社会',score.soc)}${scoreCorrectionField_('math','数学',score.math)}${scoreCorrectionField_('sci','理科',score.sci)}${scoreCorrectionField_('eng','英語',score.eng)}${scoreCorrectionField_('rank5','5科順位',score.rank5,99999)}<div class="field full score-section-title">実技4教科</div>${scoreCorrectionField_('mus','音楽',score.mus)}${scoreCorrectionField_('art','美術',score.art)}${scoreCorrectionField_('pe','体育',score.pe)}${scoreCorrectionField_('tech','技術家庭',score.tech)}${scoreCorrectionField_('rank9','9科順位',score.rank9,99999)}<div class="field full score-section-title">学校平均</div>${scoreCorrectionField_('avg_jpn','平均 国語',score.avg_jpn)}${scoreCorrectionField_('avg_soc','平均 社会',score.avg_soc)}${scoreCorrectionField_('avg_math','平均 数学',score.avg_math)}${scoreCorrectionField_('avg_sci','平均 理科',score.avg_sci)}${scoreCorrectionField_('avg_eng','平均 英語',score.avg_eng)}${scoreCorrectionField_('avg_total5','平均 5科計',score.avg_total5,500)}</div><button id="saveScoreCorrection" class="primary-button" type="submit">訂正内容を保存</button><p id="scoreCorrectionMessage" class="form-message"></p></form></div>`;$('closeDrawer').onclick=()=>root.replaceChildren();$('scoreCorrectionForm').onsubmit=async event=>{event.preventDefault();const button=$('saveScoreCorrection'),payload=Object.fromEntries(new FormData(event.target).entries());button.disabled=true;button.textContent='保存中…';try{const out=await api('saveForestaScoreCorrection',{studentId:d.student.studentId,...payload});d.scores=out.scores||[];root.replaceChildren();$('adminScoreRows').innerHTML=scoreRows(d.scores,true,false);bindScoreEditButtons_(d);toast('定期テストの成績を訂正しました。')}catch(error){$('scoreCorrectionMessage').textContent=error.message;button.disabled=false;button.textContent='訂正内容を保存'}}}
function renderAdminStudent(){const d=state.student||{},latest=d.latestLesson||{},subject=latest.subject||'数学',units=(d.units||[]).filter(u=>u.subject===subject),teachers=d.instructors||[];$('app').innerHTML=`<div class="page-head"><div><button id="backToList" class="back-button">← 本日の一覧</button><h1>${esc(d.student?.name)}さん</h1><p>${esc(d.student?.campus)}｜${esc(d.student?.grade)}｜${esc(d.student?.school)}</p></div><button id="openEntry" class="action-button primary">授業記録を入力</button></div>${d.status==='BEHIND'||d.status==='AT_SCHOOL'?'<div class="alarm-banner">⚠ 学校より先になっていません。学校進度と学習した単元を確認してください。</div>':'<div class="success-banner">✓ 学校より先の範囲を学習できています。</div>'}<div class="detail-grid"><section class="panel"><div class="panel-head"><div><span class="eyebrow">PACE</span><h2>進行計画</h2></div>${statusPill(d.status)}</div><div class="pace-line"><div class="pace-item"><span>学校進度</span><b>${esc(d.schoolProgressCode||'未入力')}</b></div><div class="pace-item"><span>フォレスタ</span><b>${esc(d.forestaProgressCode||'未入力')}</b></div><div class="pace-item"><span>残り</span><b>${esc(d.pace?.remainingUnits??'—')}単元</b></div><div class="pace-item"><span>必要ペース</span><b>${esc(d.pace?.requiredPerLesson??'—')}/回</b></div></div></section><section class="panel"><div class="panel-head"><div><span class="eyebrow">SCORES</span><h2>今回の目標点と定期テスト履歴</h2></div></div>${targetScoreForm_(d,'adminTargetScores')}<p class="help">間違いがある場合は、該当テストの「訂正」を押してください。この画面内で直せます。</p><div class="table-wrap"><table class="score-table"><thead><tr><th>テスト</th><th>英</th><th>数</th><th>5科</th><th>順位</th><th>操作</th></tr></thead><tbody id="adminScoreRows">${scoreRows(d.scores,true,d.scoresDeferred&&!d.scores?.length)}</tbody></table></div></section></div><section class="panel" style="margin-top:16px"><div class="panel-head"><div><span class="eyebrow">HOMEWORK</span><h2>前回宿題の確認結果</h2></div></div><div class="homework-list">${latest.previousHomeworkItems?.length?homeworkItems(subject,latest.previousHomeworkItems):'<div class="empty compact">確認記録はまだありません</div>'}</div></section><section class="panel" style="margin-top:16px"><div class="panel-head"><div><span class="eyebrow">HISTORY</span><h2>授業履歴</h2></div></div><div class="history-list">${(d.lessons||[]).map(x=>`<div class="history-row"><b>${esc(x.lessonDate)}｜${esc(x.subject)} ${esc(lessonUnitLabel_(x)||'単元未登録')}</b><span>CT ${esc(x.ctResult||'未実施')}｜前回宿題 ${x.homeworkCompleted==='YES'?'完了':x.homeworkCompleted==='PARTIAL'?'一部完了':x.homeworkCompleted==='NO'?'未完了':'記録なし'}｜担当 ${esc(x.instructorName||'—')}</span></div>`).join('')||'<div class="empty">授業記録はまだありません</div>'}</div></section><div id="drawerRoot"></div>`;$('backToList').onclick=renderAdmin;$('openEntry').onclick=()=>openEntryDrawer(d,subject,units,teachers);bindTargetScoreForm_('adminTargetScores',d,d.student?.studentId);bindScoreEditButtons_(d)}
function openEntryDrawer(d,subject,units,teachers){const root=$('drawerRoot');root.innerHTML=`<div class="drawer"><form id="lessonForm" class="drawer-card"><div class="drawer-head"><div><span class="eyebrow">LESSON ENTRY</span><h2>${esc(d.student.name)}さんの授業記録</h2></div><button id="closeDrawer" class="close-button" type="button">×</button></div><div class="form-grid"><label class="field"><span>授業日</span><input name="lessonDate" type="date" value="${new Date().toISOString().slice(0,10)}" required></label><label class="field"><span>科目</span><select name="subject"><option ${subject==='数学'?'selected':''}>数学</option><option ${subject==='英語'?'selected':''}>英語</option></select></label><label class="field full"><span>本日の担当者</span><select name="instructorName" required><option value="">選択してください</option>${teachers.map(t=>`<option>${esc(t.name)}</option>`).join('')}</select><p class="help">生徒の教室に合う講師だけを表示しています。</p></label><div id="lessonSubjectFields" class="subject-fields">${lessonSubjectFields_(d,subject)}</div><label class="field full"><span>クリアテスト</span><select name="ctResult"><option value="">未実施</option><option>◎</option><option>〇</option><option>×</option></select><div class="ct-guide"><b>◎ 全問正解</b><b>〇 1問間違い</b><b>× 2問以上間違い → 特訓部屋</b></div></label><label class="field full"><span>授業メモ</span><textarea name="memo" rows="3" maxlength="300"></textarea></label></div><button id="saveLesson" class="primary-button" type="submit">保存して次回宿題を作成</button><p id="entryMessage" class="form-message"></p></form></div>`;$('closeDrawer').onclick=()=>root.replaceChildren();const subjectSelect=root.querySelector('[name=subject]');subjectSelect.onchange=()=>{$('lessonSubjectFields').innerHTML=lessonSubjectFields_(d,subjectSelect.value)};$('lessonForm').onsubmit=async e=>{e.preventDefault();const button=$('saveLesson'),form=new FormData(e.target),payload=Object.fromEntries(form.entries());payload.progressUnitIds=form.getAll('progressUnitIds');payload.completedHomeworkIds=form.getAll('completedHomeworkIds');button.disabled=true;button.textContent='保存中…';try{const out=await api('saveForestaLesson',{studentId:d.student.studentId,...payload});toast(out.ctTrainingRequired?'保存しました。特訓部屋の連絡が必要です。':'授業記録と次回宿題を保存しました。');await openStudent(d.student.studentId)}catch(error){$('entryMessage').textContent=error.message;button.disabled=false;button.textContent='保存して次回宿題を作成'}}}

async function restore(){let saved=null;try{saved=JSON.parse(sessionStorage.getItem(STAFF_SESSION_KEY)||'null')}catch(e){}if(saved?.token){state.token=saved.token;state.role=saved.role;state.profile=saved.profile;try{return await(state.role==='STUDENT'?loadStudent():loadAdmin())}catch(e){sessionStorage.removeItem(STAFF_SESSION_KEY);state.token=''}}const commonToken=localStorage.getItem(COMMON_TOKEN_KEY);if(commonToken){state.token=commonToken;state.role='STUDENT';try{state.profile=JSON.parse(localStorage.getItem(COMMON_PROFILE_KEY)||'null');return await loadStudent()}catch(e){clearSession()}}}
$('loginForm').addEventListener('submit',async event=>{event.preventDefault();const role=new FormData(event.target).get('loginRole'),button=$('loginButton');button.disabled=true;button.textContent='確認中…';$('loginMessage').textContent='';try{const result=role==='student'?await api('studentLogin',{studentId:$('loginId').value.trim(),password:$('loginPassword').value}):await api('staffLogin',{code:$('loginId').value.trim(),password:$('loginPassword').value});saveSession(role,result);role==='student'?await loadStudent():await loadAdmin()}catch(error){$('loginPassword').value='';$('loginMessage').textContent=error.message}finally{button.disabled=false;button.textContent='ログイン'}});
document.querySelectorAll('[name=loginRole]').forEach(input=>input.addEventListener('change',()=>{$('loginIdLabel').textContent=input.value==='student'?'生徒ID':'講師番号'}));
$('logoutButton').addEventListener('click',()=>{const token=state.token;clearSession();if(token){state.token=token;api('logout').catch(()=>{});state.token=''}location.reload()});
restore();
